### PR TITLE
update to index and reports page

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
* updated index page - the blue text and big buttons did not look like they fit with rest of page
* updates reports page - just small changes to add headers 
* added footer to index and reports page
* fixed css for firefox

screen shot 2018-09-14 at 10 20 01 am


screen shot 2018-09-12 at 12 07 00 pm

**Comment by tsurdilo** [comment]
@mswiderski updated per our conversation. please take a look when you can .thanks.

**Comment by tsurdilo** [comment]
@mswiderski aligned the buttons to all be same class

**Comment by tsurdilo** [comment]
@mswiderski removed all font definitions except one for html/body. fonts should be aligned now.

**Comment by mswiderski** [comment]
merged manually, thanks

**Pull request closed without merging**
