### PR TITLE
adding config section close button

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski added "close" button on the config section. also small cs changes

screen shot 2018-08-28 at 11 24 46 am

**Comment by mswiderski** [comment]
Looks nice, I would just use primary button class on the read more button. 

Why did you remove the separator line? I thought it nicely breaks the content so it’s not all in one block. 

Is it possible to have just black/dark gray close button instead of the blue background?

**Comment by tsurdilo** [comment]
@mswiderski changed button class, added back separator, made button black background with white foreground. hope its ok now. thanks!

screen shot 2018-08-29 at 9 43 23 am

**Comment by mswiderski** [comment]
Thanks, can you attach screenshot as I don’t have my computer ...

**Comment by tsurdilo** [comment]
screen shot 2018-08-29 at 9 43 23 am

**Comment by tsurdilo** [comment]
@mswiderski added screenshot in last comment. thanks!

**Comment by mswiderski** [comment]
Looks perfect, last thing - can we make the play icon of the wizard (forth step) green as well? That way we keep it consistent

**Comment by tsurdilo** [comment]
@mswiderski added here is the screenshot:

screen shot 2018-08-29 at 12 50 49 pm

**Review by mswiderski — APPROVED** [review]

**Pull request merged**
