### PR TITLE
service update

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski this is a facelift of the current boopstrap services app
- replaces current demo ui with a new much more business like ui (much faster too)
- added thymeleaf as web technology as it is what boostrap is pushing so users will be familiar with it from demos. also it allows us to easily extend this to add new capabilities w/o much html+js code
- all css and js includes are local now - app will run w/o internet connection 

Here are some screenshots of new app ping me for demo too if you want


screen shot 2018-08-14 at 8 11 20 pm

screen shot 2018-08-14 at 8 11 26 pm

screen shot 2018-08-14 at 8 11 33 pm


screen shot 2018-08-14 at 8 11 39 pm


screen shot 2018-08-14 at 8 11 49 pm

**Comment by mswiderski** [comment]
@tsurdilo looks really nice, few comments:
- first impression on the landing page is that it is just too little ... white background maybe enhance this as we had in the very beginning?
- add a cancel/close button when the wizard is opened
- can we make the select box for version editable? we need to allow to put any version there
- change checkboxes for capabilities to radio buttons
- maybe use some "lighter" colours for the second step - I was actually thinking to make use of the cards (business automat, decision management and optimiser) on the landing page so once user click on them that would already mean selected capability and no need to place it on the wizard any more, wdyt? so with that second step would only be project options
- the generating app overlay seem to show only once the zip Is ready for download so looks like it's too late

anyway, this seems to be the way to go so great work

**Comment by tsurdilo** [comment]
@mswiderski you are right it looks too plain so I took your advice and changed it up a bit. Here are the screenshots:
screen shot 2018-08-15 at 1 57 21 pm
screen shot 2018-08-15 at 1 57 12 pm
screen shot 2018-08-15 at 1 56 59 pm


The version box is an editable dropdown now so users can pick or enter value themselves
Removed the "generating app" modal thingy...not needed and it didnt work correctly anyways.
Need help with this title - currently jBPM Bootstrap, we should probably call it something cool?

Let me know if this is better now ;)

**Comment by tsurdilo** [comment]
@mswiderski after the talk w/ you about the capabilities selection with buttons i realized we don't really need the fancy wizard steps or even a "default" button. I managed to make a really simple design that does everything we want and still has the "default" 1-click functionality. Hope you like it. here are screenshots

screen shot 2018-08-16 at 1 48 13 am


screen shot 2018-08-16 at 1 48 25 am

**Comment by tsurdilo** [comment]
@mswiderski ok did another update after our last conversations. here are screenshots. hope its ok now

screen shot 2018-08-17 at 1 22 46 pm

screen shot 2018-08-17 at 1 22 54 pm

screen shot 2018-08-17 at 1 23 02 pm

screen shot 2018-08-17 at 1 23 10 pm

**Comment by tsurdilo** [comment]
@mswiderski updated to blue/white theme. hope its better now

screen shot 2018-08-18 at 9 07 50 pm

screen shot 2018-08-18 at 9 07 59 pm

**Pull request closed without merging**
